skos:
  distributie_pad: ../resources/${package.replace(".","/").concat("/")}
  distributie_naam: testrepo
  jsonld_source: ../resources/source/codelijst_context.json
  csv_source: ../resources/source/codelijst_source.csv
dcat:
  distributie_pad : ../resources/be/vlaanderen/omgeving/data/id/dataset/codelijst-${codelijstId}/
  distributie_naam: catalog
  jsonld_source : ../resources/source/catalog_context.json
  csv_source : ../resources/source/catalog_source.csv

